services:
  # Backend API
  - type: web
    name: territory-conquest-api
    env: python
    region: oregon
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: STRAVA_CLIENT_ID
        sync: false
      - key: STRAVA_CLIENT_SECRET
        sync: false
      - key: STRAVA_REDIRECT_URI
        value: https://territory-conquest-api.onrender.com/api/integrations/strava/callback
      - key: BACKEND_CORS_ORIGINS
        value: '["https://territory-conquest.onrender.com","http://localhost:3000"]'
      - key: ENVIRONMENT
        value: production
